project:
  type: website
  render:
    - "*.qmd"
    - "!materials/*/exercises/"
    - "!materials/Demonstrations/"
    - "!materials/Exercise/"
    - "!materials/Presentation/"
  output-dir: docs

from: markdown+emoji

website:
  title: "Dynamic Reporting with Quarto"
  page-navigation: true
  navbar:
    background: light
    foreground: dark
    right:
      - text: "About"
        href: about.qmd
      - text: "References"
        href: references.qmd
      - icon: github
        href: https://github.com/USFWS/intro-to-quarto
        aria-label: GitHub
  sidebar:
    - title: "Materials"
      style: docked
      align: left
      contents:
          - section: "Presentations"
            contents:
            - text: "1. Welcome to Quarto"
              href: materials/1-welcome-to-quarto/index.qmd
            - text: "2. Creating Documents"
              href: materials/2-creating-documents/index.qmd
  page-footer:
    right: "This website was built with ![](assets/images/quarto_logo.png){fig-alt='Quarto' width=25}."
    left: "![](assets/images/fws_logo.png){fig-alt='FWS' width=25} [Data Management](https://doimspp.sharepoint.com/sites/fws-data/SitePages/Home.aspx)"

format: 
  html:
    theme: [default, assets/custom.scss]
    toc: false

  