project:
  type: website
  render:
    - "*.qmd"
    - "!materials/*/images/"
  output-dir: docs

from: markdown+emoji

website:
  title: "Introduction to Quarto"
  description: "An introduction of Quarto for intermediate to advanced R users seeking to develop automated reports"
  favicon: assets/images/favicon.png
  site-url: https://usfws.github.io/intro-to-quarto/
  repo-url: https://github.com/USFWS/intro-to-quarto
  issue-url: https://github.com/USFWS/intro-to-quarto/issues/new
  page-navigation: true
  navbar:
    background: light
    foreground: dark
    right:
      - text: "Prework"
        href: prework.qmd
      - text: "About"
        href: about.qmd
      - text: "References"
        href: references.qmd
      - icon: github
        href: https://github.com/USFWS/intro-to-quarto
        aria-label: GitHub
  sidebar:
    - title: "Materials"
      style: "docked"
      search: true
      align: left
      contents:
        - section: "Overview of Quarto"
          contents:
          - text: "- Slides"
            href: materials/1-overview/index.qmd
          - text: "- Exercises"
            href: materials/1-overview/exercises.qmd
  page-footer:
    right: "This website was built with [Quarto](https://quarto.org/)."

format: 
  html:
    theme: [default, assets/custom.scss]
    toc: false

  